### ISSUE TITLE
VDA 5050 Vehicle connected Failed

### ISSUE THREAD

**Issue by hzcfy** [openTCS/opentcs-integration-example#2]
VDA 5050 Vehicle connected Failed

**Comment by hzcfy** [comment]
cloneProject success，run kernel、control、modal、operations。kernelControlCenter Vehicle driver -> enable adapter-> Broker connected success，Vehicle connected Failed

**Comment by swltr** [comment]
@hzcfy When creating issues, please fill out the issue template and provide as much information as possible to help identify the problem.

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Achyut1702** [comment]
Hi Stefan Walter(https://github.com/swltr), Martin Grzenia(https://github.com/martingr)

I am working on the **openTCS-integration-Example and I tried to integrated it with VDA5050 adapter v2.0**. After Kernel, Model Editor, Operational Desk, Kernel Control Center service turned UP. I am getting in openTCS template VDA Adapter for Operational Desk as- 
![image](https://github.com/openTCS/opentcs-integration-example/assets/172021241/6f26d107-0e48-452f-bbae-018983dec5b2)

While I enable the VDA5050 adapter, the Vehicle state is still "Unknown". and My Control Center is-
![image](https://github.com/openTCS/opentcs-integration-example/assets/172021241/e801977a-088e-4f87-9973-173b74dbcbf1)

**my topic is : uagv/v2/xyz/0001/state**
This is the details I send through MQTTx-
{"headerId":11181,"timestamp":"2024-06-18T12:14:44.6046930Z","version":"2.0.0","manufacturer":"xyz","serialNumber":"0001","orderId":"","orderUpdateId":0,"lastNodeId":"","lastNodeSequenceId":0,"nodeStates":[],"edgeStates":[],"agvPosition":{"positionInitialized":true,"localizationScore":1.0,"x":-29.0,"y":-16.999998092651368,"theta":0.00019965189858339727,"mapId":"01"},"velocity":{"vx":0.0,"vy":0.0,"omega":0.0},"loads":[],"driving":false,"paused":false,"newBaseRequest":false,"distanceSinceLastNode":0.0,"actionStates":[],"batteryState":{"batteryCharge":100.0,"batteryVoltage":48.0,"batteryHealth":100.0,"charging":false},"operatingMode":"AUTOMATIC","errors":[],"information":[],"safetyState":{"eStop":"NONE","fieldViolation":false}}

**### It will connected with broker, but not with the Vehicle**. Guide me like how can I enable Vehicle connection.

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
